### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by jeromemo** [andrelucca/OctoTuya-SmartPlug#4]
Hello,
I used this plugin before (the original by ziirish) and it was great.
But now, I can't make the plugin working anymore (even with your mods). I'm always having this error on Octoprint :

![Capture d’écran 2023-04-07 à 08 30 03](https://user-images.githubusercontent.com/38230336/230554540-01209a9e-0c07-470e-a195-8b9b2eb65645.png)

I took a look at the debug log and there are errors 905, 901 and 904.
The plug is working very well in Home Assistant.

Could you please help me ?

**Comment by andrelucca** [comment]
Hello @jeromemo ,
Thanks for giving a chance to my version of the plugin, sad to hear that is not working properly as it is for me. 
I'm still going through the process of adoption of the original plugin from ziirish, and hopefully soon I'll be able to update and continue his work. In the meantime I'll do my best to help you troubleshoot your issue from here.
My mods from the original plugin, besides bugfixes, little UI improvements and a very detailed [Wiki](https://github.com/andrelucca/OctoTuya-SmartPlug/wiki) on how to use and configure it included a change on the API that communicates with Tuya, the original one after extensive research had a lot of problems and proved that point when I was testing it. So after changing this API everything worked great on my devices. But that not seems to be your case. As a suggestion I would try the following troubleshoots:

1. Reacquire the device Local Key from Tuya services, this info changes if the device is removed/readded to the Tuya/SmartLife app and may be causing your connection issue.  I detailed every step to acquire this data in the [Wiki](https://github.com/andrelucca/OctoTuya-SmartPlug/wiki/How-to-obtain-Device-ID-and-Local-Key) of the plugin
2. Uninstall completely this plugin and the original one (if you still have it) using the option from Octprint that uninstalls it and wipe all files. This proved to be a problem in my tests since both plugins share some libraries inside Octoprint and caused connections issues.
3. Check/Uncheck the option to use de protocol 3.3, this new version of the protocol proved to works better with my devices, so I recommend to test with the option checked if doesn't work try uncheking it.
4. Check the MCU version of your device, during my tests I discovered that older MCU versions have a lot of connection issues with this third-part APIs that communicates with Tuya, so I tested with a brand new plug with a very recent MCU version, and no connections issues happened. More details on this problem [here](https://github.com/andrelucca/OctoTuya-SmartPlug/wiki/How-to-obtain-Device-ID-and-Local-Key#devices-compatibility)

If none of the above works for you, you can enable the debug log from the plugin and paste the log here so I can check and try to find what's going on.
Last but not least there is a chance that the older API works better for your devices, I can provide a version of the plugin using it but it will not be an quick thing to be done and I won't be able to test it since this API didn't work with my devices, but it's worth the shot .

Keep me posted if anything solved your problem, or if you tried anything different and make it work.

**Comment by andrelucca** [comment]
Sorry to hear that none of the troubleshoots could help you @jeromemo. Thanks for sharing your logs by the way, but unfortunately I couldn't determine what's going on, actually provide better logs would be a great improvement for future releases of the plugin. I think as a last resort I'll try to make a version of the plugin using the original API from the ziirish plugin, this won't be a quick fix and hopefully I'll be able to provide it by the official plugin repository since ziirish just added me as a maintainer there. I'll leave this Issue open here so I'm able to link it as soon as I create this version. Until there if you manage to try some configuration that make the connection work let me know.

**Comment by jeromemo** [comment]
Hello @andrelucca,
I do appreciate your help and I tried version 0.3.2 from @ziirish page with no luck.
I still have the same error.
It works in home assistant with the local Tuya plugin, so credentials from Tuya Cloud API account configuration are good and i can get IDs and keys from tuya-cli wizard. So I really don't know where to look...

**Comment by jeromemo** [comment]
Hello @andrelucca,
it took a me while but I finally solved my problem. My Octoprint server was running on Windows 10 on a Mac mini that has  just died. I had to buy a Pi 4 to replace and now your plugin works like a charm with all my tuya devices.
So I guess it has something to do with a Python library after a Windows update.
Anyway, thank you very much for your help. You can close this issue.

**Comment by andrelucca** [comment]
Hello @jeromemo 

Sorry on the late response and the absence of support, the last months have been very busy at work and I was unable to check on my personal projects.

Its great news that you were able to make it work. Actually your experience give me some ideas to add on the Wiki, just to make sure that the whole setup is similiar to the one I'm using, especially this not so friendly Python libs incompatibilities.

Anyway, thanks so much for reporting your problem and giving a shot to the plugin, hope it will be useful in your projects
